### ISSUE TITLE
lepší?

### ISSUE THREAD

**Issue by Packaa** [kubaran11/3AI-2024-Car-Config#13]
![output-onlinegiftools](https://github.com/kubaran11/3AI-2024-Car-Config/assets/169641468/0a521c94-2875-4e3d-8de4-ac1c7c80d252)
![auto](https://github.com/kubaran11/3AI-2024-Car-Config/assets/169641468/1bbf90d7-0dcd-4e32-b884-c6ba2ff85681)

**Comment by kubaran11** [comment]
Teď už bude vše v #12.
