### ISSUE TITLE
gif modelu auta na levo

### ISSUE THREAD

**Issue by Packaa** [kubaran11/3AI-2024-Car-Config#9]
![output-onlinegiftools](https://github.com/kubaran11/3AI-2024-Car-Config/assets/169641468/91af6011-8c11-4b44-95fe-bf9ab75f8ebb)

**Comment by Aakuho** [comment]
Bylo by mozne upravit gif aby vypadal neprerusovane?

**Comment by Packaa** [comment]
> Bylo by mozne upravit gif aby vypadal neprerusovane?

idk zkusim to

**Comment by kubaran11** [comment]
Pokračuje se na #12, toto vlákno se uzavírá. Prosím pak už vše okolo auta řešit na #12 a nezakládat na každý příspěvek nové issue.
